apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: qprofiles
        image: qprofilesdemo/python:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:  
  name: my-nodeport-wordpress
  namespace: wordpress
spec:
  selector:    
    app.kubernetes.io/component: wordpress-webserver
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30036
    protocol: TCP
